# Generated by Django 3.2.4 on 2021-07-03 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('a_id', models.AutoField(primary_key=True, serialize=False)),
                ('awards', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed_back',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email_id', models.CharField(max_length=256, unique=True)),
                ('feed_back', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Hobbie',
            fields=[
                ('h_id', models.AutoField(primary_key=True, serialize=False)),
                ('hobbies', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=1024, unique=True)),
                ('detail', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('skills', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('workshop', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_heading', models.CharField(max_length=1024, unique=True)),
                ('p_title', models.CharField(max_length=1024)),
                ('p_discription', models.CharField(max_length=2048)),
                ('p_subhead1', models.CharField(max_length=1024)),
                ('p_sub_1_discription', models.CharField(max_length=2048)),
                ('p_subhead2', models.CharField(max_length=1028)),
                ('p_sub_2_discription', models.CharField(max_length=2048)),
                ('skill_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resumeApp.skill')),
            ],
        ),
    ]
