# Generated by Django 3.2.4 on 2021-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyObjective',
            fields=[
                ('obj_id', models.AutoField(primary_key=True, serialize=False)),
                ('objctive', models.CharField(max_length=2048, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('mp_id', models.AutoField(primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=2048, unique=True)),
            ],
        ),
    ]
